# These format settings only apply when calling format from within this module.
# If called from the top level, the top-level settings will apply.
edition = "2024"
style_edition = "2021" # 2024 is unstable
max_width = 100
wrap_comments = true
normalize_comments = true
comment_width = 100
# Forces each "use" statement to be on an individual line to reduce merge
# conflicts during active work on the repo.
imports_granularity = "Item"
